Send Triggered Job to App
cicoyle/dapr pull request #23
Opened 2024-04-24 22:24 UTC by cicoyle

Successfully sending triggered jobs back to the app via the app channel from the daprd sidecar using both grpc and http protocols.

See my [test-apps repo](https://github.com/cicoyle/test-apps) I've been using for testing where I have 2 apps, one for grpc comms and one for http where both are able to receive the triggered job.

NOTE: Draft mode until I add tests.

## Checklist

Please make sure you've  completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing
* [ ] End-to-end tests passing
* [ ] Extended the documentation / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Specification has been updated / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_
* [ ] Provided sample for the feature / Created issue in the https://github.com/dapr/docs/ repo: dapr/docs#_[issue number]_

2024-04-27 00:01 UTC, cicoyle commented on tests/integration/suite/daprd/scheduler/streaming/stream.go
> +		daprd.WithLogLevel("debug"),
I thought this test was still valuable, as it ensures that the sidecar receives the job

2024-04-29 21:58 UTC, JoshVanL requested changes

2024-04-29 21:58 UTC, JoshVanL commented on pkg/channel/grpc/grpc_channel.go
> +		return nil, err
Defer releasing ch

2024-04-29 21:58 UTC, JoshVanL commented on pkg/channel/grpc/grpc_channel.go
> +	//client.OnTriggerJobEvent() in triggerJob
Remove

2024-04-29 21:58 UTC, JoshVanL commented on pkg/channel/http/http_channel.go
> +	}
What does this do?

2024-05-02 13:28 UTC, cicoyle commented on pkg/channel/http/http_channel.go
> +	}
It's a check to ensure that the URL starts with a forward slash. I kept this check for consistency with the service invocation logic, but can rm if you feel strongly that it should be removed.

2024-05-02 13:30 UTC, cicoyle commented on pkg/channel/grpc/grpc_channel.go
> +		return nil, err
done

2024-05-02 13:47 UTC, JoshVanL approved these changes

2024-05-02 18:52 UTC, cicoyle commented on pkg/channel/http/http_channel.go
> +	}
I tried removing this and it fails the `httpcallback/run/app_receives_triggered_job` so I believe this is necessary at least for now. I'm going to merge as is.

2024-05-02 18:52 UTC, merged