Retry clients if first try fails
cicoyle/dapr pull request #29
Opened 2024-05-22 16:45 UTC by cicoyle

Add retry logic on sidecar, such that if the first connection to scheduler fails, it keeps retrying continuously since if the scheduler is enabled, it should be able to connect.

2024-05-22 17:02 UTC, elena-kolevska reviewed
Should we use one of the exponential backoff retry mechanisms we have in kit? Retrying every second forever seems a bit dangerous. It also handles not overloading the logs with errors and nice things like that.
https://github.com/dapr/kit/blob/main/retry/retry.go

2024-05-22 17:13 UTC, cicoyle commented
> nential backoff retry mechanisms we hav

It retries `client.New` after sleeping a sec, but the dialTimeout is 30s, so its really every 31s. That being said, I can switch to the backoff retry pkg if we still think its necessary, but its blocking the sidecar main thread from proceeding. I don't _think_ it should be an issue since if scheduler is enabled, it theoretically should exist and be able to connect upon the sidecar starting up, and if not it should be coming up. I am hesitant to backoff retry on the sidecar main thread logic...

2024-05-23 15:18 UTC, JoshVanL requested changes

2024-05-23 15:18 UTC, JoshVanL commented on pkg/runtime/runtime.go
> +			log.Infof("Failed to initialize scheduler clients: %s. Retrying...", err)
```suggestion
			log.Errorf("Failed to initialize scheduler clients: %s. Retrying...", err)
```

2024-05-23 15:18 UTC, JoshVanL commented on pkg/runtime/runtime.go
> +		default:
```suggestion
```

2024-05-23 15:18 UTC, JoshVanL commented on pkg/runtime/runtime.go
> +			time.Sleep(time.Second)
```suggestion
select {
			case <- time.After(time.Second):
			case <-ctx.Done():
			  return nil, ctx.Error()
			  }
```

2024-05-23 15:43 UTC, cicoyle commented on pkg/runtime/runtime.go
> +select {
I did the sign off and commit batch, but it looks like it messaged up the indentation here. let me fix that

2024-05-24 11:26 UTC, JoshVanL approved these changes

2024-05-24 13:48 UTC, merged